### ISSUE TITLE
Image provenant de Home assistant

### ISSUE THREAD

**Issue by larosecedric** [jlpouffier/home-assistant-config#4]
Bonjour, 
J'aimerai envoyer une image qui est située sur le serveur qui eberge HA (config/top/Snapshots/test1.jpg).
J'ai essayer plusieurs path sans succès. 
La notification passe bien mais pas l'image. Si je met une image provenant du web (http://...xxx.jpg) dans image_url je reçoit l'image avec dans la notification.
Pourriez-vous m'aider ?
Merci

**Comment by jlpouffier** [comment]
Désolé je ne fourni pas d'aide sur mon github

**Comment by jlpouffier** [comment]
Closed
