### ISSUE TITLE
Netflix states

### ISSUE THREAD

**Issue by mycanaletto** [jlpouffier/home-assistant-config#7]
Bonjour et bravo pour ta video sur appdaemon. J'adore appdaemon qui est trop méconnu.

Ca m'a donné l'idée de continuer la gestion de mes lumières avec Android TV
Sur Android TV le retour d'état est assez disparate (quelle que soit la méthode (Android TV Remote, ADB, Bravia, Cast)
* Netflix : toujours en playing
* Arte : OK play/Pause, etc...
* Prime : OK play/pause etc...
* Emby : nada, il faut passer par l'intégration Emby et dans mon cas ça fonctionne depuis longtemps.

Bref, je cherche une solution pour obtenir le play/pause de Netflix, et gérer les éclairages quelle que soit l'application utilisée. Idées bienvenues... Car quelle que soit la méthode (yaml, ou appdaemon, sans la source ça va pas être possible.

Et ChatGPT me dit : 
_Détecter l'état de lecture (play/pause) de Netflix sur une Android TV peut être un peu plus compliqué en raison des mesures de sécurité et de confidentialité prises par Netflix. Netflix a tendance à limiter les intégrations tierces pour des raisons de droits d'auteur et de sécurité. Par conséquent, la détection de l'état de lecture sur Netflix peut ne pas être directement prise en charge par l'intégration Android TV de Home Assistant._

Merci
lionel @ www.canaletto.fr

**Comment by jlpouffier** [comment]
J'ai fais quelque chose d'un peu plus propre maintenant.

J'utilise 2 integration differente

- [Cast](https://www.home-assistant.io/integrations/cast/)
- [Android ADB](https://www.home-assistant.io/integrations/androidtv/)

Cast est extremement rapide mais le status du player est effectivement toujours "playing" lorsque j'utilise Netflix
Android ADB est tres lent (Un polling toutes les 30 secondes environ) mais marche tout le temps, meme pour netflix.

Maintenant je mix les 2 dans un nouveau media_player grace a l'integration "[Universal Media Player](https://www.home-assistant.io/integrations/universal/)"
Voice mon "Master" media player: [Ici](https://github.com/jlpouffier/home-assistant-config/blob/master/packages/media_center/media_player_universal_media_center.yaml)

**Comment by mycanaletto** [comment]
Donc ADB remonte bien le statut de Netflix ?
Merci pour l'info, je testerais ça
